from enum import Enum



class ResponseEnums(Enum):
    
    NOT_ALLOWED_FILE_TYPE = 'NOT ALLOWED FILE TYPE'
    SIZE_EXCEEDED = "FILE SIZE EXCEEDED"
    VALIDATION_SUCESS = "VALIDATION SUCCESS"
    
    FILE_UPLOADED_SUCCESSFULLY = "FILE UPLOADED SUCCESSFULLY"
    FILE_UPLOADE_FAILED = "FILE UPLOAD FAILED"
    NO_CHUNK_FOUND = "  NO CHUNK FOUND"

    PROCESS_SUCCESS="PROCESS SUCCESS"